export const BRANDS = [
  '032c','1017 ALYX 9SM','132 5. ISSEY MIYAKE','A DICIANNOVEVENTITRE','A-COLD-WALL*',
  'A. A. Spectrum','A.P.C.','a.v. vattev','AAPE by A Bathing Ape','AARON ESH','ABRA',
  'Acne Studios','ADER error','adidas Originals','AGOLDE','AGR','Ahluwalia &PaulSmith',
  'AïE','AIREI','Akoni','ALAINPAUL','Alan Crocetti','ALEXANDER DIGENOVA','Alexander Wang',
  'AMI Paris','AMIRI','AMOMENTO','Anderson\'s','Andersson Bell','ANDREĀDAMO',
  'Ann Demeulemeester','Anna Sui','Arc\'teryx','AURALEE','AUTRY','AVAVAV','Axel Arigato',
  'Balenciaga','BALMAIN','BAO BAO ISSEY MIYAKE','BAPE','Barbour','Berner Kühl',
  'Birkenstock','Black Comme des Garçons','Bless','Bleue Burnham','Bode','BOSS',
  'Bottega Veneta','Brioni','Burberry','BYBORRE','C.P. Company','CAMPERLAB',
  'Canada Goose','Carhartt Work In Progress','Carne Bollente','CARRER','Cartier',
  'Casablanca','CASEY CASEY','Charles Jeffrey LOVERBOY','Charlie Constantinou','Chet Lo',
  'Chopova Lowena','Clarks Originals','colbo','Collina Strada','COMMAS',
  'Comme des Garçons Homme','Comme des Garçons Homme Deux','Comme des Garçons Homme Plus',
  'COMME des GARÇONS PLAY','COMME des GARÇONS WALLETS','Commission','Common Projects',
  'Converse','COOR','Coperni','Courrèges','COÛT DE LA LIBERTÉ','Craig Green',
  'Cutler and Gross','Deadwood','DET BLEV SENT','DEVOA','Diemme','Diesel','Dime',
  'Dion Lee','District Vision','Dita','doublet','Dr. Martens','Dries Van Noten',
  'Dsquared2','Dunst','ECCO.kollektive','Eckhaus Latta','Edward Cuming','EGONlab',
  'Eidos','Emanuele Bicocchi','Emporio Armani','Endless Joy','Enfants Riches Déprimés',
  'Engineered Garments','Entire Studios','Erdem','ERL','Ernest W. Baker','Études',
  'FARIS','Fear of God','Fear of God ESSENTIALS','Fendi','Ferragamo','FFFPOSTALSERVICE',
  'Filippa K','FORMA','Fred Perry','FREI-MUT','Gabriela Hearst','GAUCHERE','GCDS',
  'George Cox','Georgia Kemball','Gimaguas','Givenchy','Glass Cypress','GmbH',
  'Golden Goose','Gucci','Guest in Residence','Guidi','Han Kjobenhavn',
  'Handsome Stockholm','HARAGO','Hatton Labs','Hed Mayner','HELIOT EMIL','Helmut Lang',
  'HEREU','HODAKOVA','Holzweiler','HOMME PLISSÉ ISSEY MIYAKE','HOPE','Hugo','HYACYN',
  'IN GOLD WE TRUST PARIS','Innerraum','Isa Boulder','Isabel Marant','JACQUEMUS',
  'Jan-Jan Van Essche','Jean Paul Gaultier','JEANERICA','Jil Sander','JiyongKim',
  'Julius','Juntae Kim','Junya Watanabe','Justine Clenquet','JW Anderson',
  'Karmuel Young','KEEN','Kenzo','KHOKI','Kijun','Kiko Kostadinov','KOZABURO','Ksubi',
  'Kuboraum','Labrum','Lacoste','Lady White Co.','Lanvin','Le Gramme','LE17SEPTEMBRE',
  'LEMAIRE','Les Tien','lesugiatelier','LGN Louis Gabriel Nouchi','Liberal Youth Ministry',
  'LOEWE','LU\'U DAN','MACKAGE','Magliano','Maison Kitsuné','Maison Margiela',
  'Maison MIHARA YASUHIRO','Marcelo Burlon County of Milan','Marine Serre','Marni',
  'Marsèll','Marsèll Gomme','Marshall Columbia','Martine Rose','master-piece',
  'mastermind JAPAN','MASTERMIND WORLD','MATIÈRES FÉCALES','Maximilian Davis','McQueen',
  'Merrell 1TRL','Merz b. Schwanen','mfpen','MISBHV','MM6 Maison Margiela','MMIC',
  'Moncler','Moncler Genius','Moncler Grenoble','Moon Boot','Mordecai','Moschino',
  'Mugler','N.Hoolywood','nanamica','Nanushka','NEEDLES','Neighborhood','New Balance',
  'NICOLAS ANDREAS TARALIS','Nike','Nike Jordan','NO IDEA','NORSE PROJECTS','Nudie Jeans',
  'Numbering','Oakley','Off-White','Officine Générale','Oliver Peoples','On','OUAT',
  'OUR LEGACY','Palm Angels','Paloma Wool','Panconesi','Parajumpers','Parnell Mooney',
  'Parts of Four','Paul Smith','PDF','Perks and Mini','Peter Do','Polo Ralph Lauren',
  'Port Tanger','POST ARCHIVE FACTION (PAF)','Prada Eyewear','PS by Paul Smith','PUMA',
  'R13','rag & bone','Ralph Lauren Purple Label','RANRA','Ray-Ban','RCOS','RECODE',
  'Reese Cooper','Represent','RETROSUPERFUTURE','Rhude','Rick Owens','Rick Owens DRKSHDW',
  'Rier','Rivington Roi Rebis','ROA','RRL','sacai','SAGE NATION','Saint Laurent',
  'Salomon','Sanderlak','Satoshi Nakamoto','Saucony','Saul Nash','SC103','Second/Layer',
  'Séfr','Serapis','Seventh','Simone Rocha','SIRE','Solid Homme','Song for the Mute',
  'SONIA CARRASCO','South2 West8','ssstein','Stanley Raffington','Stefan Cooke',
  'Still Kelly','Stockholm (Surfboard) Club','Stolen Girlfriends Club','Stone Island',
  'Studio Nicholson','Sunflower','SUNNEI','Swampgod','System',
  'TAKAHIROMIYASHITA TheSoloist.','Tekla','The Elder Statesman','The North Face',
  'The Row','THEBE MAGUGU','Theory','Thom Browne','thom/krom','Thug Club',
  'title of work','Toga Virilis','TOM FORD','Tom Wood','TONYWACK','Toogood',
  'UNDERCOVER','Undercoverism','Valentino','Valentino Garavani','Vans','VAQUERA',
  'VEERT','VEJA','Versace','Versace Jeans Couture','VETEMENTS','VINNY\'s','visvim',
  'VITELLI','Vivienne Westwood','vowels','Wales Bonner','We11done','Who Decides War',
  'WILLY CHAVARRIA','Won Hundred','WOOYOUNGMI','WTAPS','XENIA TELUNTS','Y\'s For Men',
  'Y-3','Y/Project','YAKU','YOHJI YAMAMOTO','YOKE','YUME YUME','ZANKOV','ZEGNA',
];
